// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmqwq8wevSGDZzAjItjT8z6cflAlqepM',
    appId: '1:460684467319:web:eff02613c3678c11b0fa72',
    messagingSenderId: '460684467319',
    projectId: 'rideshareapp-6b6f9',
    authDomain: 'rideshareapp-6b6f9.firebaseapp.com',
    storageBucket: 'rideshareapp-6b6f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Nqv0mM_AcD6i7QmXtY18D7h0D5QaZF0',
    appId: '1:460684467319:android:4c1d4c70cd65c761b0fa72',
    messagingSenderId: '460684467319',
    projectId: 'rideshareapp-6b6f9',
    storageBucket: 'rideshareapp-6b6f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuR6h59yGs3m6dahFPKBne8qDtLcGf9Wg',
    appId: '1:460684467319:ios:7a30fac0ea5ee277b0fa72',
    messagingSenderId: '460684467319',
    projectId: 'rideshareapp-6b6f9',
    storageBucket: 'rideshareapp-6b6f9.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuR6h59yGs3m6dahFPKBne8qDtLcGf9Wg',
    appId: '1:460684467319:ios:7a30fac0ea5ee277b0fa72',
    messagingSenderId: '460684467319',
    projectId: 'rideshareapp-6b6f9',
    storageBucket: 'rideshareapp-6b6f9.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmqwq8wevSGDZzAjItjT8z6cflAlqepM',
    appId: '1:460684467319:web:a28a11562526a915b0fa72',
    messagingSenderId: '460684467319',
    projectId: 'rideshareapp-6b6f9',
    authDomain: 'rideshareapp-6b6f9.firebaseapp.com',
    storageBucket: 'rideshareapp-6b6f9.firebasestorage.app',
  );
}
